### PR TITLE
Dead (404) link updated

### PR DESCRIPTION
**Pull request by e-aldo**
Dead (404) link updated in Note "Enrolling Samsung Knox devices may require you to enable access to Samsung servers.".

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @e-aldo  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
Hi @e-aldo 

Could you please provide more information about the change? We've checked the current link and your modified link and both goes to the same site.

Kind regards, Microsoft C&E Localization Team

**Comment by e-aldo** [comment]
Hi @v-radelg, 

before my updated, i test the existing link (https://support.samsungknox.com/hc/fr/articles/115013833108-Our-corporate-devices-are-behind-a-firewall-How-do-I-enable-Knox-Workspace-devices-to-contact-Samsung-servers) and it was not working.

i search the good topic and update the link with the good link (https://support.samsungknox.com/hc/en-us/articles/115013575167-Our-corporate-devices-are-behind-a-firewall-How-do-I-allow-Knox-services-to-contact-Samsung-servers-).

**Comment by v-radelg** [comment]
Hello @e-aldo ,

Considering that the current link works properly there's no need to make modifications. 

We truly appreciate your suggestion and will gladly review your future ones.

Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

**Comment by e-aldo** [comment]
Hello @v-radelg, 

Welcome. It is ok for me to forbide the suggestion. I add for future issue the screenshot of error that i get with current link.



Kind regards,
Aldo

**Pull request closed without merging**
